#Sean Wagner
#BIF400
#3/14 In Class Exercise
use strict;
use warnings;

#get input string
my $inputString = "GTTGTCTGAAGGCGGTCCCTCCCCACGATTACCGTACGGTGGACTTGTGCTACCCGACTCACTATCCAGAGTCGGTTACCCGAAAGTGAGTAAACTAGGACGAACTTCACGCCGGCAATGGGATCTGTAAAGGCCCCCCCGTTTAGCCCTCCGTAGTCCGGACTCATTTACGCATAGAACGGGTGCAGAATTGAGACCACCTATCCCAGGCCTTTCCTTCGTAAAATCAGGCGATAGACTATCCTAGTGTATTAACAGCCCGCCCACGGAGCCACGGAATGCGCAGAGCCATGCAGAGTCGTCGACAACTCGGAGAGTCCAATCTGCTGAGCGTTGTGTCCCCTCTGGAATGCAACGTCCACTTCGGCCAGGTGGTGTTAGCGACGTGCCAGGAGGGCTGCTGCAAGCCCAACCACATTCCGACGGTGGTGACATGCGCGTAAATACCACCGAAGTAGGGACGACCTGGATCAATTTGGATTACGGTGTCTCCGGTGGCCCTCGCACGTGCAGTCCTTAGGGCCCGTCGGCTGCATCTTGATGCTGACATATTTCGTGCTTTGGAGCGCCATTTCCAAATACTCTGCAGTTCCTACAGTGGTAGACCAACCTTCTTGAATAGACCGCGGGTAATAGGTACTGGCGAGAGGCGTAAGACAACGCCATTCGGTCCCCGGTTCTTGAAGTGGCTATGTGAATGACATCAGCCGAGTGACAGAACTACGCTTCCTAGTCCGAACGGTTTGTTGCTTACTTCTCAATGCGCTCGGCATTATCAAACGGAGGCATCTATTTTGCACATGTCCTAATTTAGTGCGACGCCAGTTCTCTTAGCGGACGCCCCGGTCTAACTACCATGATTGATAAATGACTGCACTCCGTATCCCGGGCTGCGCACGAATCCGGCCTCGGGCACACCCGGCTCGAAAAGGAAGTGGACGATGGGCTGATAGCGTTTATCGGATCCCGCGGTTGAGGCCTTCGCACCTCTAGACGATGC";
#get length of kmers
my $kmerLen = 50;
#output list
my @kmers;
#runs through everything and gets the substrings
for(my $i = 0; $i < length($inputString) - $kmerLen + 1; $i++) {
	my $outS = substr($inputString, $i, $kmerLen);
	push @kmers, $outS;
}
#sorts them
@kmers = reverse(sort(@kmers));
#prints it out
while(@kmers) {
	print pop @kmers,"\n";
}